#ifndef EBNF_LEXER_H
#define EBNF_LEXER_H

#include "lexer.h"

typedef enum {
	E_DEFINING_SYMBOL = '=',
	E_CONCATENATE_SYMBOL = ',',
	E_TERMINATOR_SYMBOL = ';',
	E_DEFINITION_SEPARATOR_SYMBOL = '|',
	E_START_GROUP_SYMBOL = '(',
	E_END_GROUP_SYMBOL = ')',
	E_START_REPETITION_SYMBOL = '{',
	E_END_REPETITION_SYMBOL = '}',
	E_START_OPTION_SYMBOL = '[',
	E_END_OPTION_SYMBOL = ']',
	E_REPETITION_SYMBOL = '*',
	E_EXCEPT_SYMBOL = '-',
	E_WHITE_SPACE = 256,
	E_COMMENT,
	E_INTEGER,
	E_META_IDENTIFIER,
	E_TERMINAL_STRING,
	E_SPECIAL_SEQUENCE,
	E_CHARACTER_SET
} EBNFToken;

void ebnf_lexer(Lexer *lexer, Token *token);

#endif //EBNF_LEXER_H
